---
- name: "[ PHP-FPM | Install ]"
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php5-cli
    - php5-common
    - php5-mysql
    - php5-gd
    - php5-fpm
    - php5-cgi
    - php5-fpm
    - php-pear
    - php5-mcrypt