---
- name: "[ MySQL Server | Install ]"
  apt:
    name: "{{ mysql_packages }}"
    update_cache: yes
    state: present

- name: "[ MySQL Server | Add user ]"
  mysql_user:
    name: "{{ db_admin_user }}"
    password: "{{ db_admin_user_pass }}"
    state: present
  ignore_errors: yes

- name: "[ MySQL Server | Create DB ]"
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: "{{ db_admin_user }}"
    login_password: "{{ db_admin_user_pass }}"
    state: present

- name: "[ MySQL Server | Add WordPress user ]"
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_user_pass }}"
    login_user: "{{ db_admin_user }}"
    login_password: "{{ db_admin_user_pass }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present